import { AIChatMessage } from "@/types";
import { mockTeams } from "@/lib/mock-data/teams";
import { mockJudges } from "@/lib/mock-data/judges";
import { mockIncidents } from "@/lib/mock-data/incidents";
import { mockVenues } from "@/lib/mock-data/venues";

/**
 * AI Assistant & Operational Copilot API Service
 * 
 * Grounded in actual mock event data (turnstile attendance, judge workloads, room availability, incidents).
 * Responses are explicitly identified as generated by the mock AI service.
 * 
 * TODO: Wire to FastAPI AI reasoning agent endpoint when available:
 * - POST /api/v1/assistant/chat
 */
export const assistantApi = {
  async processQuery(query: string): Promise<AIChatMessage> {
    await new Promise((r) => setTimeout(r, 500));
    const q = query.toLowerCase();

    // 1. Who has not checked in? / Absent teams
    if (q.includes("not checked in") || q.includes("who has not") || q.includes("absent")) {
      const absentTeams = mockTeams.filter((t) => t.checkInStatus === "ABSENT" || t.checkInStatus === "NOT_CHECKED_IN").slice(0, 6);
      return {
        id: `ai-msg-${Date.now()}`,
        sender: "AI",
        timestamp: new Date().toISOString(),
        content: `Found ${absentTeams.length} teams that have not checked in yet. Their assigned suites remain reserved but unclaimed.`,
        structuredData: {
          type: "ABSENT_TEAMS",
          payload: {
            count: absentTeams.length,
            teams: absentTeams.map((t) => ({
              id: t.id,
              name: t.name,
              room: t.assignedVenueName || t.assignedVenue || "R001",
              bench: t.assignedBench || "B001",
            })),
          },
        },
        suggestedActions: [
          { label: "Dispatch SMS Reminder to Team Leads", actionType: "SEND_SMS" },
          { label: "Release Unclaimed Benches to Waitlist", actionType: "RELEASE_BENCHES" },
        ],
      };
    }

    // 2. Room conflicts / Sessions conflicts
    if (q.includes("conflict") || q.includes("room conflict") || q.includes("session")) {
      return {
        id: `ai-msg-${Date.now()}`,
        sender: "AI",
        timestamp: new Date().toISOString(),
        content: "Schedule telemetry detected 1 active room conflict: Workshop 'CP-SAT Constraint Programming' in Lab 101 has 45 registered attendees, exceeding maximum room capacity of 40.",
        structuredData: {
          type: "ROOM_AVAILABILITY",
          payload: [
            {
              session: "CP-SAT Constraint Programming Workshop",
              room: "Lab 101 (Von Neumann Suite)",
              capacity: 40,
              enrolled: 45,
              recommendation: "Migrate session to Hall B (capacity: 80) which has a free window at 11:00 AM.",
            },
          ],
        },
        suggestedActions: [
          { label: "Migrate Session to Hall B", actionType: "MIGRATE_SESSION" },
          { label: "Cap Registrations at 40", actionType: "CAP_ENROLLMENT" },
        ],
      };
    }

    // 3. Which judges are overloaded?
    if (q.includes("overload") || q.includes("judge") || q.includes("fatigue")) {
      const overloadedJudges = mockJudges.filter((j) => j.workloadStatus === "OVERLOADED" || j.workload >= 80);
      return {
        id: `ai-msg-${Date.now()}`,
        sender: "AI",
        timestamp: new Date().toISOString(),
        content: `Workload inspection indicates ${overloadedJudges.length} judges operating above the 80% capacity threshold. Standard deviation across jury panels is σ = 0.62.`,
        structuredData: {
          type: "JUDGE_OVERLOAD",
          payload: overloadedJudges.map((j) => ({
            id: j.id,
            name: j.name,
            organization: j.organization,
            workloadPct: j.workload,
            status: j.workloadStatus,
            teamsAssigned: j.assignedTeams.length,
          })),
        },
        suggestedActions: [
          { label: "Execute OR-Tools Re-Balance Optimizer", actionType: "REBALANCE_JUDGES" },
          { label: "Activate Standby Judge J010", actionType: "ACTIVATE_STANDBY" },
        ],
      };
    }

    // 4. Critical incidents
    if (q.includes("incident") || q.includes("critical") || q.includes("emergency")) {
      const openIncidents = mockIncidents.filter((i) => i.status !== "RESOLVED");
      return {
        id: `ai-msg-${Date.now()}`,
        sender: "AI",
        timestamp: new Date().toISOString(),
        content: `There are currently ${openIncidents.length} open incidents. 1 is classified as CRITICAL (Circuit breaker tripped in Room R002).`,
        structuredData: {
          type: "INCIDENT_SUMMARY",
          payload: openIncidents.map((i) => ({
            id: i.id,
            title: i.title,
            priority: i.priority,
            location: i.location,
            status: i.status,
          })),
        },
        suggestedActions: [
          { label: "Page Technical Lead (Sarah Jenkins)", actionType: "PAGE_TECH" },
          { label: "Open Emergency Control Center", actionType: "OPEN_CONTROL_CENTER" },
        ],
      };
    }

    // 5. Default grounded operational reply
    return {
      id: `ai-msg-${Date.now()}`,
      sender: "AI",
      timestamp: new Date().toISOString(),
      content: `I parsed: "${query}". Based on live event telemetry: 114 of 120 teams are checked in (95% attendance), 20 active judges are reviewing Round 1, and 24 rooms are online. Use the suggested actions below to explore deeper.`,
      suggestedActions: [
        { label: "Who has not checked in?", actionType: "QUERY_ABSENT" },
        { label: "Which sessions have room conflicts?", actionType: "QUERY_CONFLICTS" },
        { label: "Which judges are overloaded?", actionType: "QUERY_JUDGES" },
      ],
    };
  },
};

// Backward compatibility alias for aiApi
export const aiApi = assistantApi;
