import {
  HardConstraint,
  SoftConstraint,
  OptimizationConfig,
  OptimizationResults,
  AllocationMatrixRow,
} from "@/types";

export const defaultHardConstraints: HardConstraint[] = [
  {
    id: "hc-01",
    name: "Zero Judge Double-Booking",
    description: "A judge cannot be scheduled to evaluate more than one team in the same time slot.",
    enabled: true,
    severity: "CRITICAL",
  },
  {
    id: "hc-02",
    name: "Room & Bench Exclusive Occupancy",
    description: "No two teams can occupy the same bench simultaneously.",
    enabled: true,
    severity: "CRITICAL",
  },
  {
    id: "hc-03",
    name: "Conflict of Interest Avoidance",
    description: "Strictly prohibit judges from evaluating teams with declared alumni, company, or mentorship ties.",
    enabled: true,
    severity: "CRITICAL",
  },
  {
    id: "hc-04",
    name: "Hard Hardware Prerequisite Matching",
    description: "Teams requiring dedicated 3-phase power or RF shielding must only be assigned to certified rooms.",
    enabled: true,
    severity: "CRITICAL",
  },
  {
    id: "hc-05",
    name: "Judge Maximum Evaluation Capacity",
    description: "No judge can be assigned more teams than their contractual max capacity limit.",
    enabled: true,
    severity: "CRITICAL",
  },
];

export const defaultSoftConstraints: SoftConstraint[] = [
  {
    id: "sc-01",
    name: "Domain Expertise Alignment",
    description: "Pair teams with evaluators having verified high semantic similarity to the project domain.",
    weight: 9,
    enabled: true,
  },
  {
    id: "sc-02",
    name: "Balanced Judge Workload Distribution",
    description: "Minimize standard deviation of assigned teams across all available judges (target σ < 0.8).",
    weight: 8,
    enabled: true,
  },
  {
    id: "sc-03",
    name: "Venue Proximity Clustered by Domain",
    description: "Cluster teams of similar technical tracks into adjacent rooms for smoother judge transit.",
    weight: 7,
    enabled: true,
  },
  {
    id: "sc-04",
    name: "Consecutive Slot Minimization (Judge Fatigue)",
    description: "Provide at least one 15-minute buffer between successive deep evaluations.",
    weight: 6,
    enabled: true,
  },
];

export const defaultOptimizationConfig: OptimizationConfig = {
  algorithm: "CP-SAT",
  maxRuntimeSeconds: 15,
  balanceJudgeWorkloadWeight: 8,
  domainMatchWeight: 9,
  consecutiveSlotWeight: 6,
  venueProximityWeight: 7,
};

export const mockAllocationMatrix: AllocationMatrixRow[] = [
  {
    id: "alloc-001",
    teamId: "T042",
    teamName: "Team T042 — BioSense Glucose Predictor",
    domain: "HealthTech & Bio",
    venueId: "R004",
    venueName: "Room 204 - Claude Shannon Wing",
    benchId: "B042",
    benchLabel: "Bench 42",
    judgeIds: ["J007", "J012"],
    judgeNames: ["Elena Rostova (BioGenomics)", "Chloe Dupont (Venture Partner)"],
    timeSlot: "08:00 PM - 08:30 PM",
    round: 1,
    status: "OPTIMAL",
    score: 98.4,
    satisfactionNotes: "100% domain affinity match. Zero conflict of interest. Power prerequisites satisfied.",
  },
  {
    id: "alloc-002",
    teamId: "T001",
    teamName: "Team T001 — NeuralPulse Edge AI",
    domain: "AI / Machine Learning",
    venueId: "R001",
    venueName: "Room 101 - Turing Hall",
    benchId: "B001",
    benchLabel: "Bench 01",
    judgeIds: ["J001", "J002"],
    judgeNames: ["Dr. Marcus Vance (MIT)", "Siddharth Rao (DeepMind)"],
    timeSlot: "02:00 PM - 02:30 PM",
    round: 1,
    status: "OPTIMAL",
    score: 99.1,
    satisfactionNotes: "Direct LLM/Edge compute specialization match.",
  },
  {
    id: "alloc-003",
    teamId: "T005",
    teamName: "Team T005 — AeroMesh Drone Network",
    domain: "IoT & Robotics",
    venueId: "R002",
    venueName: "Room 102 - Turing Hall",
    benchId: "B005",
    benchLabel: "Bench 05",
    judgeIds: ["J003", "J013"],
    judgeNames: ["Dr. Aris Thorne (Stanford)", "Kenji Sato (Sony AI)"],
    timeSlot: "02:30 PM - 03:00 PM",
    round: 1,
    status: "OPTIMAL",
    score: 96.8,
    satisfactionNotes: "Autonomous hardware & sensors expert panel.",
  },
  {
    id: "alloc-004",
    teamId: "T012",
    teamName: "Team T012 — HyperLedger Zero-Knowledge",
    domain: "Distributed Systems / Web3",
    venueId: "R003",
    venueName: "Room 201 - Von Neumann Hall",
    benchId: "B012",
    benchLabel: "Bench 12",
    judgeIds: ["J005", "J011"],
    judgeNames: ["David O'Connor (Ethereum)", "Rajesh Kannan (Azure)"],
    timeSlot: "03:00 PM - 03:30 PM",
    round: 1,
    status: "CONFLICT_RESOLVED",
    score: 93.5,
    satisfactionNotes: "Judge J006 had conflict; auto-rerouted to J011 with no latency delay.",
  },
  {
    id: "alloc-005",
    teamId: "T018",
    teamName: "Team T018 — Sentrix Cloud Neutralizer",
    domain: "CyberSecurity",
    venueId: "R005",
    venueName: "Room 205 - Claude Shannon Wing",
    benchId: "B018",
    benchLabel: "Bench 18",
    judgeIds: ["J006", "J014"],
    judgeNames: ["Amina Al-Mansoor (AWS)", "Sarah Al-Hassan (CISO)"],
    timeSlot: "03:30 PM - 04:00 PM",
    round: 1,
    status: "OPTIMAL",
    score: 97.2,
    satisfactionNotes: "Zero trust security profile matched with AWS solutions leader.",
  },
  {
    id: "alloc-006",
    teamId: "T033",
    teamName: "Team T033 — VoltGuard Smart Grid",
    domain: "CleanTech & Green Energy",
    venueId: "R007",
    venueName: "Room 301 - Ada Lovelace Wing",
    benchId: "B033",
    benchLabel: "Bench 33",
    judgeIds: ["J009", "J018"],
    judgeNames: ["Liam Gallagher (CleanGrid)", "Fatima Zahra (Siemens)"],
    timeSlot: "04:00 PM - 04:30 PM",
    round: 1,
    status: "OPTIMAL",
    score: 95.9,
    satisfactionNotes: "Grid storage & renewable domain alignment verified.",
  },
];

export const mockOptimizationResults: OptimizationResults = {
  totalTeamsAllocated: 120,
  unallocatedTeamsCount: 0,
  hardConstraintViolations: 0,
  softConstraintSatisfactionPct: 96.8,
  overallScorePct: 98.2,
  judgeWorkloadStandardDeviation: 0.62,
  venueUtilizationPct: 94.5,
  runtimeMs: 1420,
  matrix: mockAllocationMatrix,
  conflicts: [
    "Conflict in Slot B resolved: Judge J006 declared mentorship with T012; swap succeeded with Judge J011.",
    "Hardware requirement for Team T005 accommodated in certified Room R002.",
  ],
  aiInsights: [
    "CP-SAT solver achieved zero hard constraint violations across 120 teams in 1.42s.",
    "Judge workload standard deviation lowered from 2.14 (manual baseline) to 0.62 (balanced).",
    "Average transit time between assigned rooms for judges reduced by 44%.",
  ],
};
