import { EventItem } from "@/types";

export const mockEvents: EventItem[] = [
  {
    id: "evt-01",
    organizationId: "org-tkr",
    name: "VISTRA Hackathon 2026",
    type: "Hackathon",
    description: "Global 36-hour flagship hackathon bringing together 120 top innovation teams to solve challenges in Generative AI, Distributed Systems, FinTech, and CleanTech.",
    startDate: "2026-10-15T08:00:00Z",
    endDate: "2026-10-17T20:00:00Z",
    registrationDeadline: "2026-10-10T23:59:59Z",
    status: "LIVE",
    expectedParticipants: 500,
    registeredTeamsCount: 120,
    currentRound: 1,
    totalRounds: 3,
    venuesCount: 24,
    judgesCount: 20,
    bannerUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80",
    rounds: [
      {
        id: "rnd-01",
        name: "Round 1 — Code & Architecture Screening",
        order: 1,
        status: "IN_PROGRESS",
        startTime: "2026-10-15T14:00:00Z",
        endTime: "2026-10-15T19:00:00Z",
        qualifyingQuota: 48,
        criteria: [
          { id: "crt-01", name: "Technical Feasibility & Architecture", maxScore: 25, weight: 0.25, description: "System design, clean code, latency considerations, scalability." },
          { id: "crt-02", name: "Novelty & Innovation", maxScore: 25, weight: 0.25, description: "Originality of approach, unique value proposition." },
          { id: "crt-03", name: "Execution Completeness", maxScore: 25, weight: 0.25, description: "Working demo prototype, core flow functionality." },
          { id: "crt-04", name: "Domain Alignment", maxScore: 25, weight: 0.25, description: "Depth of understanding and relevance to challenge track." },
        ],
      },
      {
        id: "rnd-02",
        name: "Round 2 — Deep-Dive Prototype & Live Demo",
        order: 2,
        status: "UPCOMING",
        startTime: "2026-10-16T10:00:00Z",
        endTime: "2026-10-16T16:00:00Z",
        qualifyingQuota: 12,
        criteria: [
          { id: "crt-05", name: "Live Execution & Resilience", maxScore: 30, weight: 0.3, description: "Resilience under stress testing, edge-case handling." },
          { id: "crt-06", name: "UI/UX & User Experience", maxScore: 30, weight: 0.3, description: "Design elegance, user ergonomics, clarity of interaction." },
          { id: "crt-07", name: "Impact & Market Viability", maxScore: 40, weight: 0.4, description: "Real-world deployability, TAM analysis, commercial viability." },
        ],
      },
      {
        id: "rnd-03",
        name: "Round 3 — Grand Finale & Jury Pitch",
        order: 3,
        status: "UPCOMING",
        startTime: "2026-10-17T14:00:00Z",
        endTime: "2026-10-17T18:00:00Z",
        qualifyingQuota: 3,
        criteria: [
          { id: "crt-08", name: "Pitch Clarity & Q&A Defense", maxScore: 40, weight: 0.4, description: "Ability to articulate vision, handle scrutiny, defend tech stack." },
          { id: "crt-09", name: "Disruptive Potential", maxScore: 60, weight: 0.6, description: "10x paradigm shift, game-changing potential in industry." },
        ],
      },
    ],
    timeSlots: [
      { id: "ts-01", label: "Slot A (02:00 PM - 03:15 PM)", startTime: "14:00", endTime: "15:15", roundId: "rnd-01", capacity: 40 },
      { id: "ts-02", label: "Slot B (03:30 PM - 04:45 PM)", startTime: "15:30", endTime: "16:45", roundId: "rnd-01", capacity: 40 },
      { id: "ts-03", label: "Slot C (05:00 PM - 06:15 PM)", startTime: "17:00", endTime: "18:15", roundId: "rnd-01", capacity: 40 },
      { id: "ts-04", label: "Slot D (06:30 PM - 07:30 PM)", startTime: "18:30", endTime: "19:30", roundId: "rnd-01", capacity: 20 },
    ],
    rules: [
      { id: "rul-01", title: "Original Codebase Requirement", description: "All code must be authored during the hackathon. Open-source libraries and pretrained models are allowed with declaration.", category: "CODE_OF_CONDUCT", isMandatory: true },
      { id: "rul-02", title: "All-Member Physical Check-In", description: "At least 75% of registered team members must scan their unique QR badge at registration desks to be eligible for bench allocation.", category: "ELIGIBILITY", isMandatory: true },
      { id: "rul-03", title: "Hardware Safety Protocols", description: "High-voltage equipment or unshielded RF transmitters must pass technical safety inspection in Room R001 before powering on.", category: "HARDWARE", isMandatory: true },
    ],
  },
  {
    id: "evt-02",
    organizationId: "org-01",
    name: "Enterprise AI Summit & Tech Expo 2026",
    type: "Conference",
    description: "Annual corporate summit showcasing breakthrough advancements in autonomous agents, data governance, and cloud infrastructure.",
    startDate: "2026-11-05T09:00:00Z",
    endDate: "2026-11-07T18:00:00Z",
    registrationDeadline: "2026-10-30T23:59:59Z",
    status: "PUBLISHED",
    expectedParticipants: 1200,
    registeredTeamsCount: 65,
    currentRound: 1,
    totalRounds: 1,
    venuesCount: 12,
    judgesCount: 15,
    bannerUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80",
    rounds: [],
    timeSlots: [],
    rules: [],
  },
  {
    id: "evt-03",
    organizationId: "org-02",
    name: "Inter-University Robotic Combat & Tech Fest",
    type: "College Fest",
    description: "Inter-collegiate technical robotics championship, autonomous drone navigation, and algorithmic speed coding battles.",
    startDate: "2026-12-01T08:30:00Z",
    endDate: "2026-12-03T19:00:00Z",
    registrationDeadline: "2026-11-20T23:59:59Z",
    status: "DRAFT",
    expectedParticipants: 800,
    registeredTeamsCount: 30,
    currentRound: 1,
    totalRounds: 2,
    venuesCount: 8,
    judgesCount: 10,
    bannerUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80",
    rounds: [],
    timeSlots: [],
    rules: [],
  },
  {
    id: "evt-personal-01",
    organizationId: null,
    ownerId: "usr-01",
    isPersonalEvent: true,
    name: "My Coding Workshop",
    type: "Workshop",
    description: "Hands-on weekend intensive deep dive into Full-Stack Next.js 16, TypeScript, and AI agents for junior developers and creators.",
    startDate: "2026-10-12T10:00:00Z",
    endDate: "2026-10-12T17:00:00Z",
    registrationDeadline: "2026-10-11T23:59:59Z",
    status: "PUBLISHED",
    expectedParticipants: 50,
    registeredTeamsCount: 42,
    currentRound: 1,
    totalRounds: 1,
    venuesCount: 1,
    judgesCount: 2,
    location: "Online / Hybrid Studio Room 4",
    bannerUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&auto=format&fit=crop&q=80",
    rounds: [],
    timeSlots: [],
    rules: [],
  },
  {
    id: "evt-personal-02",
    organizationId: null,
    ownerId: "usr-01",
    isPersonalEvent: true,
    name: "Community Meetup",
    type: "Community Event",
    description: "Monthly open community gathering to network, share lightning talks, and showcase open source side projects.",
    startDate: "2026-10-20T17:30:00Z",
    endDate: "2026-10-20T21:00:00Z",
    registrationDeadline: "2026-10-19T23:59:59Z",
    status: "UPCOMING",
    expectedParticipants: 100,
    registeredTeamsCount: 85,
    currentRound: 1,
    totalRounds: 1,
    venuesCount: 2,
    judgesCount: 3,
    location: "Tech Hub Auditorium, Level 2",
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=1200&auto=format&fit=crop&q=80",
    rounds: [],
    timeSlots: [],
    rules: [],
  },
];

export const mockPersonalEvents: EventItem[] = mockEvents.filter(
  (e) => e.isPersonalEvent || e.organizationId === null
);
