import { Incident } from "@/types";

export const mockIncidents: Incident[] = [
  {
    id: "INC-2041",
    eventId: "evt-01",
    title: "Access Point 3B Intermittent Packet Drop",
    category: "NETWORK",
    priority: "CRITICAL",
    status: "IN_PROGRESS",
    reportedBy: "Team T018 Lead (Devon Zhang)",
    location: "Room 205 - Claude Shannon Wing",
    assignedTo: "Sarah Jenkins (Technical Staff)",
    description: "High jitter (>280ms) and sporadic 15% packet loss on AP-3B during model checkpoint download. Affecting 3 teams.",
    createdAt: "2026-10-15T11:20:00Z",
    updatedAt: "2026-10-15T11:42:00Z",
  },
  {
    id: "INC-2042",
    eventId: "evt-01",
    title: "Tripped 24V Breaker on Bench Row 8",
    category: "POWER",
    priority: "HIGH",
    status: "ASSIGNED",
    reportedBy: "Carlos Mendez (Lead Volunteer)",
    location: "Room 102 - Turing Hall",
    assignedTo: "Facilities Electrics Team",
    description: "Two simultaneous high-draw drone battery chargers tripped secondary circuit breaker on Bench 38-40.",
    createdAt: "2026-10-15T12:05:00Z",
    updatedAt: "2026-10-15T12:10:00Z",
  },
  {
    id: "INC-2043",
    eventId: "evt-01",
    title: "HDMI Presentation Dongle Missing in Room 204",
    category: "HARDWARE",
    priority: "MEDIUM",
    status: "OPEN",
    reportedBy: "Judge J007 (Dr. Elena Rostova)",
    location: "Room 204 - Claude Shannon Wing",
    assignedTo: undefined,
    description: "Primary USB-C to dual HDMI splitter missing on presenter podium before Round 1 demo.",
    createdAt: "2026-10-15T13:10:00Z",
    updatedAt: "2026-10-15T13:10:00Z",
  },
  {
    id: "INC-2040",
    eventId: "evt-01",
    title: "Registration Badge Printer Thermal Roll Jam",
    category: "FACILITY",
    priority: "LOW",
    status: "RESOLVED",
    reportedBy: "Aisha Patel (QR Specialist)",
    location: "Main Registration Atrium",
    assignedTo: "Carlos Mendez",
    description: "Ribbon roller misaligned on Desk 2 Zebra printer. Fixed and recalibrated.",
    createdAt: "2026-10-15T08:15:00Z",
    updatedAt: "2026-10-15T08:35:00Z",
    resolvedAt: "2026-10-15T08:35:00Z",
    resolutionNotes: "Replaced ribbon roller assembly with spare from Cache B.",
  },
  {
    id: "INC-2039",
    eventId: "evt-01",
    title: "Participant Mild Burn from Soldering Iron",
    category: "MEDICAL",
    priority: "HIGH",
    status: "RESOLVED",
    reportedBy: "Liam O'Brian (Hardware Escort)",
    location: "Hardware Vault Lab 102",
    assignedTo: "Paramedic On-Site Unit",
    description: "Minor first-degree thermal burn on left thumb while prototyping sensor harness.",
    createdAt: "2026-10-15T10:00:00Z",
    updatedAt: "2026-10-15T10:20:00Z",
    resolvedAt: "2026-10-15T10:20:00Z",
    resolutionNotes: "Cold compress applied and sterile dressing wrapped. Participant cleared to continue.",
  },
];
