import { Organization, UserRole } from "@/types";

export interface OrganizationInvitation {
  code: string;
  organizationId: string;
  organizationName: string;
  organizationType: string;
  subtype: string;
  invitedRole: UserRole;
  invitedBy: string;
  expiresAt: string;
}

export const mockOrganizations: Organization[] = [
  {
    id: "org-tkr",
    name: "TKR College of Engineering & Technology",
    type: "Institution",
    subtype: "College",
    description: "Premier engineering institution hosting annual tech fests, state hackathons, job melas, and national robotics symposiums.",
    country: "India",
    city: "Hyderabad",
    website: "https://tkrcet.ac.in",
    size: "1000+",
    plan: "Enterprise",
    activeEventsCount: 4,
    membersCount: 156,
    ownerId: "usr-01",
    contactEmail: "admin@tkrcet.ac.in",
    contactPhone: "+91 40 6558 7555",
    createdAt: "2024-08-10T09:00:00Z",
  },
  {
    id: "org-abc",
    name: "ABC Technologies Inc.",
    type: "Business",
    subtype: "Company",
    description: "Enterprise software and cloud infrastructure leader organizing developer hackathons, internal innovation sprints, and partner summits.",
    country: "India",
    city: "Bengaluru",
    website: "https://abctechnologies.io",
    size: "500-1000",
    plan: "Enterprise",
    activeEventsCount: 2,
    membersCount: 64,
    ownerId: "usr-01",
    contactEmail: "events@abctechnologies.io",
    contactPhone: "+91 80 4123 4567",
    createdAt: "2024-10-15T10:30:00Z",
  },
  {
    id: "org-01",
    name: "VISTRA Global Tech & Innovations",
    type: "Business",
    subtype: "Enterprise",
    description: "Multi-national innovation network driving open-source AI competitions, corporate tech summits, and research symposiums.",
    country: "United States",
    city: "San Francisco",
    website: "https://vistratech.io",
    size: "500-1000",
    plan: "Enterprise",
    activeEventsCount: 2,
    membersCount: 48,
    ownerId: "usr-01",
    contactEmail: "contact@vistratech.io",
    contactPhone: "+1 415-555-0199",
    createdAt: "2025-01-15T09:00:00Z",
  },
  {
    id: "org-02",
    name: "National Institute of Advanced Technology",
    type: "Institution",
    subtype: "University",
    description: "Autonomous university conducting inter-university tech fests and academic conferences.",
    country: "India",
    city: "Bengaluru",
    website: "https://niat.ac.in",
    size: "1000+",
    plan: "Enterprise",
    activeEventsCount: 3,
    membersCount: 112,
    ownerId: "usr-04",
    createdAt: "2024-11-20T10:30:00Z",
  },
  {
    id: "org-04",
    name: "Open Future Foundation",
    type: "Community",
    subtype: "NGO",
    description: "Global non-profit community driving tech for social good, open-source development, and civic hacking.",
    country: "Germany",
    city: "Berlin",
    website: "https://openfuture.org",
    size: "10-50",
    plan: "Free",
    activeEventsCount: 1,
    membersCount: 16,
    ownerId: "usr-02",
    createdAt: "2025-03-01T11:00:00Z",
  },
];

export const mockInvitations: OrganizationInvitation[] = [
  {
    code: "INV-TKR-2026",
    organizationId: "org-tkr",
    organizationName: "TKR College of Engineering & Technology",
    organizationType: "Institution",
    subtype: "College",
    invitedRole: "COORDINATOR",
    invitedBy: "Dr. D. V. Rao (Principal & Director of Ops)",
    expiresAt: "2026-11-30T23:59:59Z",
  },
  {
    code: "INV-ABC-CORP",
    organizationId: "org-abc",
    organizationName: "ABC Technologies Inc.",
    organizationType: "Business",
    subtype: "Company",
    invitedRole: "EVENT_ADMIN",
    invitedBy: "Sarah Chen (VP Developer Relations)",
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    code: "INV-COMM-2026",
    organizationId: "org-04",
    organizationName: "Open Future Foundation",
    organizationType: "Community",
    subtype: "NGO",
    invitedRole: "VOLUNTEER",
    invitedBy: "Elena Rostova (Community Lead)",
    expiresAt: "2026-10-31T23:59:59Z",
  },
  {
    code: "INV-JURY-2026",
    organizationId: "org-tkr",
    organizationName: "TKR College of Engineering & Technology",
    organizationType: "Institution",
    subtype: "College",
    invitedRole: "JUDGE",
    invitedBy: "Dean of Academic Evaluation",
    expiresAt: "2026-11-15T23:59:59Z",
  },
];
