import { ResourceItem } from "@/types";

export const mockResources: ResourceItem[] = [
  {
    id: "res-01",
    eventId: "evt-01",
    name: "Day 1 Dinner Meal Boxes (Continental & Veg)",
    category: "FOOD",
    totalQuantity: 650,
    allocatedQuantity: 600,
    consumedQuantity: 412,
    unit: "Boxes",
    location: "Main Dining Hall Depot",
    lowStockThreshold: 100,
    status: "HEALTHY",
  },
  {
    id: "res-02",
    eventId: "evt-01",
    name: "Midnight Energy Drinks & Cold Brew",
    category: "FOOD",
    totalQuantity: 1200,
    allocatedQuantity: 1200,
    consumedQuantity: 980,
    unit: "Cans",
    location: "Snack Stations 1, 2 & 3",
    lowStockThreshold: 250,
    status: "LOW_STOCK",
  },
  {
    id: "res-03",
    eventId: "evt-01",
    name: "NVIDIA Jetson Orin Nano Dev Kits",
    category: "HARDWARE",
    totalQuantity: 30,
    allocatedQuantity: 28,
    consumedQuantity: 28,
    unit: "Units",
    location: "Hardware Vault Lab 102",
    lowStockThreshold: 5,
    status: "LOW_STOCK",
  },
  {
    id: "res-04",
    eventId: "evt-01",
    name: "Hacker Welcome Swag Kits & Hoodies",
    category: "KIT",
    totalQuantity: 550,
    allocatedQuantity: 500,
    consumedQuantity: 480,
    unit: "Kits",
    location: "Registration Depot North",
    lowStockThreshold: 50,
    status: "HEALTHY",
  },
  {
    id: "res-05",
    eventId: "evt-01",
    name: "RFID NFC Participant Badges",
    category: "BADGE",
    totalQuantity: 600,
    allocatedQuantity: 520,
    consumedQuantity: 495,
    unit: "Badges",
    location: "Badge Printing Station",
    lowStockThreshold: 80,
    status: "HEALTHY",
  },
  {
    id: "res-06",
    eventId: "evt-01",
    name: "Ultra-High Wattage 16A Surge Protectors",
    category: "HARDWARE",
    totalQuantity: 80,
    allocatedQuantity: 76,
    consumedQuantity: 76,
    unit: "Units",
    location: "Electrical Cache A",
    lowStockThreshold: 10,
    status: "LOW_STOCK",
  },
  {
    id: "res-07",
    eventId: "evt-01",
    name: "Digital Foil Winner Certificates (Pre-printed)",
    category: "CERTIFICATE",
    totalQuantity: 150,
    allocatedQuantity: 45,
    consumedQuantity: 0,
    unit: "Certificates",
    location: "Secretariat Lockbox",
    lowStockThreshold: 20,
    status: "HEALTHY",
  },
];
