import { Volunteer, VolunteerTask } from "@/types";

export const mockVolunteers: Volunteer[] = [
  {
    id: "vol-01",
    eventId: "evt-01",
    name: "Carlos Mendez",
    phone: "+1 415-555-0873",
    email: "carlos.m@student.edu",
    role: "Lead Floor Marshal",
    zone: "Building A - Turing Hall",
    currentShift: "Morning Shift (08:00 AM - 02:00 PM)",
    assignedTasksCount: 5,
    completedTasksCount: 3,
    status: "ON_DUTY",
  },
  {
    id: "vol-02",
    eventId: "evt-01",
    name: "Aisha Patel",
    phone: "+1 415-555-0912",
    email: "aisha.p@student.edu",
    role: "QR Check-in Specialist",
    zone: "Main Registration Atrium",
    currentShift: "Morning Shift (08:00 AM - 02:00 PM)",
    assignedTasksCount: 6,
    completedTasksCount: 5,
    status: "ON_DUTY",
  },
  {
    id: "vol-03",
    eventId: "evt-01",
    name: "Liam O'Brian",
    phone: "+1 415-555-0723",
    email: "liam.ob@student.edu",
    role: "Hardware & AV Escort",
    zone: "Building B - Von Neumann",
    currentShift: "Evening Shift (02:00 PM - 08:00 PM)",
    assignedTasksCount: 4,
    completedTasksCount: 1,
    status: "ON_DUTY",
  },
  {
    id: "vol-04",
    eventId: "evt-01",
    name: "Jessica Chen",
    phone: "+1 415-555-0618",
    email: "jessica.c@student.edu",
    role: "Food & Refreshments Lead",
    zone: "Cafeteria & Dining Hall",
    currentShift: "Morning Shift (08:00 AM - 02:00 PM)",
    assignedTasksCount: 4,
    completedTasksCount: 4,
    status: "ON_BREAK",
  },
  {
    id: "vol-05",
    eventId: "evt-01",
    name: "Tariq Mansour",
    phone: "+1 415-555-0439",
    email: "tariq.m@student.edu",
    role: "Judge Concierge",
    zone: "VIP Jury Lounge & Level 3",
    currentShift: "Evening Shift (02:00 PM - 08:00 PM)",
    assignedTasksCount: 3,
    completedTasksCount: 2,
    status: "ON_DUTY",
  },
];

export const mockVolunteerTasks: VolunteerTask[] = [
  {
    id: "tsk-01",
    title: "Verify Desk 3 QR Scanner Hardware",
    description: "Ensure Bluetooth handheld scanner is synced with terminal T3 at Main Gate.",
    zone: "Main Registration Atrium",
    priority: "HIGH",
    status: "COMPLETED",
    assignedVolunteerId: "vol-02",
    assignedVolunteerName: "Aisha Patel",
    dueTime: "08:30 AM",
  },
  {
    id: "tsk-02",
    title: "Escort Judge J007 to Room R004",
    description: "Meet Dr. Elena Rostova at VIP Lounge and guide to Claude Shannon Lab for Round 1.",
    zone: "VIP Jury Lounge & Level 3",
    priority: "URGENT",
    status: "IN_PROGRESS",
    assignedVolunteerId: "vol-05",
    assignedVolunteerName: "Tariq Mansour",
    dueTime: "01:45 PM",
  },
  {
    id: "tsk-03",
    title: "Distribute Jetson Nano Kits to Room R002",
    description: "Deliver 6 hardware development boards with 24V adapters to IoT Track benches.",
    zone: "Building B - Von Neumann",
    priority: "HIGH",
    status: "ASSIGNED",
    assignedVolunteerId: "vol-03",
    assignedVolunteerName: "Liam O'Brian",
    dueTime: "02:15 PM",
  },
  {
    id: "tsk-04",
    title: "Replenish Water Stations & Power Strips in R005",
    description: "Restock hydration cooler and provide two 16A extension cords.",
    zone: "Building A - Turing Hall",
    priority: "MEDIUM",
    status: "ACCEPTED",
    assignedVolunteerId: "vol-01",
    assignedVolunteerName: "Carlos Mendez",
    dueTime: "03:00 PM",
  },
  {
    id: "tsk-05",
    title: "Lunch Distribution Batch A Count & Audit",
    description: "Count Veg and Non-Veg boxed lunches at Section B pickup line.",
    zone: "Cafeteria & Dining Hall",
    priority: "MEDIUM",
    status: "COMPLETED",
    assignedVolunteerId: "vol-04",
    assignedVolunteerName: "Jessica Chen",
    dueTime: "12:00 PM",
  },
];
